### ISSUE TITLE
Get code migrated from other repo

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#1]

**Comment by aulneau** [comment]
We should transfer the repository from `blockstackpbc` to the `blockstack` acccount rather than copy and pasting/migrating the code (someone who has write access in both orgs would need to do so, and I believe this repository `blockstack/app.co` would need to be deleted first) see https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

**Comment by vsund** [comment]
Since there are already issues here (not sure how the things look at the other repository), the alternative would be to push the other branches into this repository (did this a few times without problems).

It would be a simple `git push https://github.com/blockstack/app.co master:master` (_not tested_).
