### ISSUE TITLE
Viewing all platforms and categories—how are these ordered? Can we order them according to # of apps or some smarter measure?

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#124]

**Comment by jeffdomke** [comment]
Checking this now. Gaia is the 1rst platform. That is because it has the most cumulative tweets per week?

**Comment by hstove** [comment]
It uses monthly visits. There must have been an issue with my rankings script last night, because now all apps have no similarweb data. The script runs into rate limit issues with similarweb sometimes and I've had to tweak it to work with that, but maybe it still failed last night. Their API has been a bit off and on and there are no docs about their rate limit, so I've had to debug it at times. I'm running the script now and it all works. We'll have to keep an eye on this.
