### ISSUE TITLE
Add in intersection observer polyfill for app mining animations

### ISSUE THREAD

**Issue by aulneau** [blockstack/app.co#199]
Safari and other browsers don't support intersection observer natively, so we need to polyfill it to allow for our nice section animations to work across all browsers.

https://github.com/w3c/IntersectionObserver/tree/master/polyfill

**Comment by markmhx** [comment]
Which animations are these? I don't see any animations in Chrome on Mac 😲

**Comment by hstove** [comment]
Yeah, I removed them because we didn't have this polyfill. Do you remember when we were really close to launch, and you couldn't view the mining page on your phone? Or any browser other than desktop chrome? That was this issue. It was related to some animations that happened when you scrolled on the mining page.

**Comment by markmhx** [comment]
Ah okay, given I can't even remember these, I think best to simply close this out and we can raise the issue again in the future if we have a yearning for animations.
