### ISSUE TITLE
Track outgoing link clicks in our DB

### ISSUE THREAD

**Issue by shea256** [blockstack/app.co#23]
Currently we're unable to see the top apps where clicks take users because we're using blank targets that open new tabs. With Google Analytics its useful to see a new path or an exit to a new domain when the user clicks on an app.

Another option would be to do what Product Hunt does with an intermediary page/modal but that takes building and will have to wait until a future version.

**Comment by hstove** [comment]
I've edited this issue because I just added google analytics event tracking for outgoing clicks, so the new goal here (as discussed with Ryan) is to track clicks in our database. This will allow us to later do data analysis on user behavior and incorporate that into a custom ranking.

**Comment by markmhx** [comment]
I'm closing this issue out in favor of https://github.com/blockstack/app.co/issues/85 since Segment integration will include outbound-link tracking. We can use Mixpanel as a Segment integration to [export the data](https://mixpanel.com/help/reference/exporting-raw-data) or [query it raw](https://mixpanel.com/jql/) as needed.
