### ISSUE TITLE
Add a Public Api for 3rd Parties to grab DApp info

### ISSUE THREAD

**Issue by MichaelFedora** [blockstack/app.co#25]
Something like [GraphQL](https://graphql.org/) would be great, but a standard REST api would do fine as well.

As a tool-developer it would be great to have access to a repository of dapps instead of having to fetch it from the Blockstack Browser server-thing (https://blockstack-browser-server.appartisan.com/data) and other hackish ways.

---

I don't know how you have your data structured but here are some ideas:

**REST**:

 - `GET: /api/v1/apps`: Gets all the dapps (limit of 100)
 - `GET: /api/v1/apps?start={start index}&count={count}` with start being >= 0, and count being 0 < count <= 100; would get `count` apps from the `start` index.
 - `GET: /api/v1/apps?protocols={array of tags}`: Gets all the dapps that depend on the protocols in the array
   - e.x. `GET: /api/v1/apps?protocols=["blockstack"]`: Gets all the dapps that depend on blockstack
 - `GET: /api/v1/apps?category={category}`: Gets all the dapps that are in the category
   - e.x. `GET: /api/v1/apps?category="business"`: Gets all the dapps that are in the business category

Obviously these params could be combined to create a request like thus:
`GET: /api/v1/apps?start=6&count=5&protocols=["blockstack"]&category="business"`
 - Gets 5 of the blockstack dapps that are in the business category, starting at number 6.

**GraphQL**:

I don't know what your data model is, so below is just an example request.

`GET: /api/v1/graphql` with the body of:
```graphql
{
  apps(start: 6, count: 5, protocols: ["blockstack"], category: "business") {
    name,
    iconUrl,
    description,
    protocols
  }
}
```

---

Lastly, I have no idea if this is a dupe of #18 because the title is incredibly confusing/vague and there's no description, so if it is I apologize in advance.

**Comment by hstove** [comment]
In regards to #18, I understand that it's a confusing title because we're talking about an app called [SimilarWeb](https://www.similarweb.com/) that provides an API for web traffic data. But that's unrelated to this.

In regards to your request, we already have a public, undocumented API 😄 !

Right now it's at [https://app-co-api.herokuapp.com/api/apps](https://app-co-api.herokuapp.com/api/apps). There is no pagination, but pagination is unnecessary because there are only 200 apps, and I don't think we'll be into the 1000's in the near term. Similarly, since there is so little data, I think it's OK to just do filtering (by category for example) on the client side.

We'll have a proper URL for that API endpoint later today (likely at data.app.co/api/apps ).

I'm going to go ahead and close this, but if there is something that you still think we should have, go ahead and comment and we can keep this discussion going.

Thanks for reaching out!

**Comment by MichaelFedora** [comment]
Nice! Is the API going to move to github eventually so we can be involved in it (raising issues, prs, getting notified when it's updated, etc)?

By the way, you still have some artifacts left in your data models: `blockchain`, `authentication`, and `storageBackend` fields are on some but not on others; I assume they're from moving over to `blockchainId`, `authenticationNetworkId`, and `storageNetworkID`... 😅

Otherwise, thanks for letting me know it exists!

**Comment by MichaelFedora** [comment]
This has yet to be implemented still.. 🙁

**Comment by hstove** [comment]
Hey! I am working on getting a public repo for the API server, I just don't have permissions in this organization to do that right now.

As far as the attributes like `blockchainID` - those are legit, and they are the actual `enum` ID that we use in our database. Then `blockchain` is the string version of that. You can see the int-to-string mapping in the `appConstants` attribute in the API.

**Comment by MichaelFedora** [comment]
Ah, gotcha; thanks for the status update! Keep me updated =)

**Comment by hstove** [comment]
Finally got it all set up!

Here's the API repo: https://github.com/blockstack/app.co-api

We have some very basic docs in the README for this repo and the API repo. If you end up setting up a local environment, let me know if you run into any hiccups and I'll try and help you and document that stuff.
