### ISSUE TITLE
Remove maximum width limitation from app nav on App Mining monthly results page

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#271]
So that the nav is allowed to expand width-wise along with the body content.

See: https://app.co/app-mining/september-2018

## Before

<img width="1427" alt="screen shot 2018-10-16 at 13 05 32" src="https://user-images.githubusercontent.com/28991/47012324-5d69db80-d144-11e8-9484-ddc4297d7e91.png">

## After

<img width="1421" alt="screen shot 2018-10-16 at 13 06 49" src="https://user-images.githubusercontent.com/28991/47012331-5fcc3580-d144-11e8-862d-6a201d818ac2.png">

**Comment by aulneau** [comment]
@markmhx I think if we do this here, we should consider doing it throughout the rest of the application.

I think the design and layout of the page breaks down on larger screens, which is why I recommended adding the max-width we have on the rest of the site to these pages:

![screen shot 2018-10-16 at 7 16 04 am](https://user-images.githubusercontent.com/11803153/47015777-7e660880-d113-11e8-9890-7a47926dd050.png)
