### ISSUE TITLE
Clarify registration input label in submission form

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#311]
The Add your app form has a checkbox which is unclear:

- [ ]  Registration is open to all users

Be more specific. What does it mean _all users_ ? All users with a Blockstack id? All users with an identity? What if there are multiple types of registration allowed?

**Comment by markmhx** [comment]
Providing link and screenshot here:

https://app.co/submit

<img width="841" alt="screen shot 2018-11-26 at 10 40 15" src="https://user-images.githubusercontent.com/28991/49005711-abbcc200-f167-11e8-90cc-f547cb1ed3e9.png">

My suggestion may be to change the label to "User registration is open to the general public".

**Comment by moxiegirl** [comment]
I'd be more specific:

_Your application's registration is open to the general public_

If they don't set this? Are they disqualified from app mining?

**Comment by markmhx** [comment]
To be clear, the form linked above (at https://app.co/submit) is *not* for App Mining specifically but rather for App.co in general. The App Mining form itself is here: https://app.co/mining.

However, in the above form, if user doesn't check this box, I believe their app will *not* be listed on App.co generally (and consequently, can't be qualified for App Mining either since listing on App.co is required for App Mining qualification).

I agree that we should reject their submission here if they don't check this box, but that goes back to adding validation per https://github.com/blockstack/app.co/issues/134.

**Comment by moxiegirl** [comment]
@markmhx Yeah, I hadn't realized that when I saw this....but we had that discussion in slack this morning.  

So, yeah, but I think my suggested rephrasing still works. It is a misconception that brevity is indicative of clarity.  So, my recommendation is a specific sentence.
