### ISSUE TITLE
Use app.co registration flow for App Mining registration

### ISSUE THREAD

**Issue by aulneau** [blockstack/app.co#339]
We are ditching the registration modal on app mining and moving over to using the main app.co app submission form. I'm not exactly sure the changes that are required to do this. 

Some initial questions:

- are there any inputs missing on the current app.co for app mining
- how does an app that is currently on app.co but not registered for app mining, register?

@jeffdomke @GinaAbrams @pstan26 can you please provide guidance / comments for this?

**Comment by GinaAbrams** [comment]
We'll need to add the terms.  Other than that, no items missing, but have some ideas about communication: 

- Instead of "registration is open to all users" -> "publicly accessible and user-ready?"

- And at the bottom, could have a note "Apps with Blockstack Auth can qualify for App Mining." 

Think there might have to be another checkbox to indicate interest in app mining or something similar. In the current model, they need to register to receive an email to provide a BTC address and W-9 (all done manually).

**Comment by jeffdomke** [comment]
Gina's comments sound good to me. Assuming we will include that info in the App Mining Kit and we should also probably send a response or welcome email to every app submission including the kit as well but 2 different emails. Will add tickets for that. cc @cuevasm
