### ISSUE TITLE
Mods to App.co registration

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#340]
Per https://github.com/blockstack/app.co/issues/339

**Comment by jeffdomke** [comment]
Instead of "registration is open to all users" -> "publicly accessible and user-ready?"

If auth = blockstack then show: Add App Mining terms to the bottom of the form and check to accept.

**Comment by aulneau** [comment]
- Add validation
- add name field

**Comment by moxiegirl** [comment]
@GinaAbrams @jeffdomke  "publicly accessible and user-ready" is a complex way of saying "registration is open to all users"

In particular, "user-ready" is unclear. What exactly does this mean? Ready for what? How do we define not ready?

Recall, not all developers are English speaking.  When possible, better to go with simple language.

**Comment by GinaAbrams** [comment]
Ah, okay. To me, "registration is open to all users" was unclear....I had to ask Hank about it in the past. I've also noticed on the admin side that a number of app developers have not been checking it off. Maybe its an anomaly, but not sure if there is a better to communicate it. 🤔 

What if we made it around sign-in instead of registration?

**Comment by moxiegirl** [comment]
_Available to use by any web or mobile user._
