### ISSUE TITLE
Submit button copy. `Done` or `Add my app`

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#401]
![Screen Shot 2019-01-07 at 11:54 PM](http://marker.screenshots.prod.s3.amazonaws.com/2f0a09e249fb4403bc3a9b425ec21b41-1546905292325.png)
---
### More Info

**Source URL**: [https://app.co/submit](https://app.co/submit)

**Comment by aulneau** [comment]
^ cc @jeffdomke

**Comment by jeffdomke** [comment]
https://uxmovement.com/forms/why-your-form-buttons-should-never-say-submit/

I want to say years back I read a post with data showing that the click through on `submit` was poor. Also "get started" 

Still feel the same?

**Comment by aulneau** [comment]
Yeah I def feel that and if it was any other kind of form I think it would apply here, eg a newsletter form, submit would not make sense. 

I think this might be an application of the rule that actually makes sense, they're submitting an app to be listed, it's not guaranteed that the app will appear in app.co. I don't mean to nit so deeply on a single button, I don't really have a huge preference.

'Get Started' doesn't make sense in my mind because what are they starting? they have no next steps.

'Add my app' is almost correct aside from the possibility that it won't be listed

'Done' makes the most sense other than 'submit app' in my mind. I can put that in.

**Comment by jeffdomke** [comment]
Sorry I was unclear. I just meant that "Get Started" is also a common CTA and it has poor conversion. Not suggesting it here. 

`Submit app` is fine with me. 
`Add my app` also seems fine to me. It's what the user is here to do.
