### ISSUE TITLE
Prevent apps from disappearing from admin homepage

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#43]
When I load the homepage of the admin panel, all apps appear momentarily but then disappear entirely:

<img width="1707" alt="screen shot 2018-07-24 at 16 47 59" src="https://user-images.githubusercontent.com/28991/43146394-710b7f6a-8f61-11e8-87d2-abd9ba772c3e.png">

@hstove is this a known bug?

I'm in Chrome on Mac.

**Comment by markmhx** [comment]
Some extra context from the console:

<img width="1705" alt="screen shot 2018-07-24 at 16 55 22" src="https://user-images.githubusercontent.com/28991/43147069-7134f286-8f62-11e8-8411-112f921ed961.png">

**Comment by hstove** [comment]
This is happening because it loads the public API list of apps (which is cached), then it makes an authenticated call to get admin-level apps (which includes pending and rejected apps). The second authenticated request fails, because you "aren't" an admin. But, if you are logged in with `markhendrickson.id`, it should work fine. Can you confirm you're using that ID to log in?

**Comment by markmhx** [comment]
yep that's the ID i'm using

**Comment by hstove** [comment]
I figured out the issue, your username is `markmhendrickson.id` with an `m` 👍 

> Also, if I'm understanding correctly, can't only admins view this page in general? I'm not sure why these two queries would check for admin-ness separately.

This is a technical detail and I know it's not very intuitive. Basically, the front-end server keeps a cache of public apps, and lists that on page load. Then, the front end client requests the admin list on page load. This is because only the client side keeps auth info right now. It's a limitation to how the auth was setup, and will actually be fixed based on some changes Thomas is doing.

**Comment by markmhx** [comment]
Good catch =)

So anyone with a Blockstack ID can authenticate and see what I saw basically? We don't verify admin status upon sign in of admin app?

**Comment by hstove** [comment]
Yes, but they can’t see anything that isn’t available on the public site and public API. They can’t see any pending apps or anything.

**Comment by markmhx** [comment]
@hstove I just tried this again and the apps still disappear suddenly for me. Can you check that the username fix you made is in place? I logged out and back in and same problem.

**Comment by markmhx** [comment]
This now works!
