### ISSUE TITLE
Admin changes for STX info

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#517]
- STX Address
- Has accepted terms
- Has collected KYC

**Comment by markmhx** [comment]
These admin options display for me on staging and I'm able to save new values. @timstackblock please confirm on your end as well.

**Comment by timstackblock** [comment]
@hstove for some reason when I restore account tjrwells.id.blockstack it opens another account see a video of the issue here https://screencast-o-matic.com/watch/cq1bYtTGIX 

This is the account you set with the admin privileges

please set the admin privileges on twellsjr.id.blockstack I cannot test this without admin privileges

**Comment by timstackblock** [comment]
Testing blocked by https://github.com/blockstack/app.co/issues/536

**Comment by markmhx** [comment]
@timstackblock I believe this can be tested again

**Comment by timstackblock** [comment]
This works closing this ticket
