### ISSUE TITLE
Re-add SEO meta tags to platform / category pages

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#52]
i.e. the title of these pages should be `Ethereum apps` or `Wallet apps`

**Comment by markmhx** [comment]
I'm not sure why this is tagged with "Design" – does it need design guidance?

**Comment by hstove** [comment]
It doesn't need design guidance, but it needs to be shipped with our redesign. We can remove the tag, but it should be in the redesign project.

**Comment by markmhx** [comment]
Ah got it. I thought those with "Design" were those requiring design guidance.

**Comment by markmhx** [comment]
This looks good in general, just noticing that "IPFS" is not fully uppercased, appearing instead as "Ipfs" in the browser title and on-page:

<img width="665" alt="screen shot 2018-07-30 at 13 40 30" src="https://user-images.githubusercontent.com/28991/43395372-241a5f72-93fe-11e8-9308-9406223686bd.png">

Is this due to a code or content problem on staging? I'm seeing it render okay on production:

<img width="744" alt="screen shot 2018-07-30 at 13 41 00" src="https://user-images.githubusercontent.com/28991/43395390-358aa546-93fe-11e8-901a-53d5d8f40dad.png">

**Comment by markmhx** [comment]
I'm noticing this for ZeroNet too so presumably we're coercing the capitalization in the view in a way that needs fixing:

<img width="560" alt="screen shot 2018-07-30 at 13 45 50" src="https://user-images.githubusercontent.com/28991/43395618-f7c0de28-93fe-11e8-874d-c99b8b375ec0.png">

Let's fix this as part of this issue even if it's not 100% the same thing as meta tags.
