### ISSUE TITLE
Maker Portal - update payment info

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#526]

**Comment by markmhx** [comment]
@hstove I'm not sure what to test here?

**Comment by hstove** [comment]
The "Payment Details" tab - you should be able to update info, and the info should be saved. The new info should be displayed in the admin page.

**Comment by markmhx** [comment]
Works for me

**Comment by timstackblock** [comment]
@hstove for some reason when I restore account tjrwells.id.blockstack it opens another account see a video of the issue here https://screencast-o-matic.com/watch/cq1bYtTGIX 

This is the account you set with the admin privileges

please set the admin privileges on twellsjr.id.blockstack I cannot test this without admin privileges

**Comment by timstackblock** [comment]
This works I will close this out
