### ISSUE TITLE
Styling issues of search results

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#55]
- The alignment of the search result rows is a little off on the left
- Show # of results instead of just 'apps'
- Show 'no results'

**Comment by hstove** [comment]
@markmhx for design help on 'no results'

**Comment by markmhx** [comment]
# Search results

Let's make the following style changes to improve search result formatting across desktop and mobile:

## Desktop

Right padding increased to 100px:

<img width="1534" alt="screen shot 2018-08-01 at 12 40 32" src="https://user-images.githubusercontent.com/28991/43517379-c46f7e5e-9588-11e8-9bcd-d4956249e10e.png">

## Mobile

Padding changed to "16px 32px" and maximum height is increased to 100%:

<img width="1550" alt="screen shot 2018-08-01 at 12 47 51" src="https://user-images.githubusercontent.com/28991/43517492-36045d82-9589-11e8-83f9-a7ba18d3ab66.png">

# Number of results

We can change the "Apps" label to show the number of results:

<img width="454" alt="screen shot 2018-08-01 at 12 50 53" src="https://user-images.githubusercontent.com/28991/43517585-8a618b3e-9589-11e8-9917-e1a2ccc52525.png">

# No results

This is how we can show "no results" instead of the number:

<img width="1221" alt="screen shot 2018-08-01 at 12 42 47" src="https://user-images.githubusercontent.com/28991/43517408-d98c65f4-9588-11e8-8da7-b42500b702b9.png">

# No underlines for results

And finally, let's remove all text underlines from all results across mobile and desktop.

**Comment by markmhx** [comment]
Looking good, just noticing that it says "No results" while results are actually loading still.

Can we wait to load the results before we update that value so that "No results" doesn't show temporarily and confuse the user?
