### ISSUE TITLE
Need two flows for signing participant agreement: U.S. and International

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#565]

**Comment by markmhx** [comment]
Is this required for release?

**Comment by GinaAbrams** [comment]
Yes.

**Comment by markmhx** [comment]
Here's what I'm seeing on staging now:

![Screen Shot 2019-07-10 at 11.23.14.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/f30b07bc-83bd-461c-8de6-afa76a31503c)

The biggest issue with this checkbox approach appears to be that there's no way to change your selection. So if I submit this form with the checkbox mistakenly set, I can't reverse. 

Instead of a checkbox in this form, perhaps we should we go with the same UX pattern as we're using on "Tax Documents" wherein we show two navigation buttons for US vs. non-US _after_ we've collected the user's name in the above form (sans checkbox)?

![Screen Shot 2019-07-10 at 11.26.52.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/447c7506-a1e4-4d8c-b0e8-2cfd8f9a2f2b)

That way, the user can take care of the name submission step first, then afterwards they can navigate back and forth between the US and non-US forms as they please.

**Comment by hstove** [comment]
Hey Mark, I wasn't able to implement the flow for 'resetting' the participation flow today. I made a new ticket to track that work at #580. I am going to move this ticket back into review, since the original goal is completed.

**Comment by markmhx** [comment]
Ok no worries, I've added another related issue here as well for adding form validation since it appears no values are currently required as well: https://github.com/blockstack/app.co/issues/581
