### ISSUE TITLE
Add progress bar shown during all state transitions

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#68]
The progress bar should have a design similar to the "BarLoader" shown here but shown at the very top of the viewport and extended to full width:

http://www.davidhu.io/react-spinners/

It should also go about 3x faster.

**Comment by markmhx** [comment]
Love it

**Comment by hstove** [comment]
@aulneau I see you removed this, was there a reason why? Some pages still take a sec or two to load and it feels stuck. Maybe there are performance enhancements we're not using on some links.

**Comment by aulneau** [comment]
I removed this because if we are doing things correctly (eg prefetching pages etc with the link component), then after the first initial page load, there will be no other network requests for data when navigating pages. There are network requests for images, and currently they all load at different speeds (because they are not optimized and coming from many locations). I think the only thing the navigation bar would be good for is the images.

A pushback that I heard was the loading bar we were using (nprogress), seems like it would just be covered up with the loading bar on mobile. On desktop, you should be able to see that the page is still loading from all the cues the browser gives you.

Also please make sure to be testing page speed (and the need/desire for a loader) on stage. Testing it on your local version will always be slow (1+second times for navigating a page), but on staging/prod it should be nearly instant. If you do find a page that _isn't_ instant, then we should look at it and ensure it is being prefetched.

**Comment by hstove** [comment]
> On desktop, you should be able to see that the page is still loading from all the cues the browser gives you.

But since it's in Javascript there aren't any cues, at least when using Next links. That's my main reason for wanting a progress bar. There is also a delay to render and redraw the component.

I'll leave this one in the backlog until we come to consensus.

**Comment by aulneau** [comment]
Yeah, the biggest reason why I removed it was if the load is less than 400ms (which it should be), the flash of the progress bar seems more like a mistake than something to help the user.

**Comment by markmhx** [comment]
> I removed this because if we are doing things correctly (eg prefetching pages etc with the link component), then after the first initial page load, there will be no other network requests for data when navigating pages. There are network requests for images, and currently they all load at different speeds (because they are not optimized and coming from many locations). I think the only thing the navigation bar would be good for is the images.

I'm seeing app modals load instantaneously, so I presume all data for them is prefetched as you describe. But I notice a discernible delay when loading category or platform pages from the homepage in particular. Are these pages supposed to be prefetched as well?

If we can prefetch *all* content / states that could possibly be loaded from any given state across the site, then I agree we can probably avoid introducing a progress bar. And I say "probably" since I'd want to ensure the delay to render and redraw that @hstove describes above is indiscernible as well.

But if we aren't able to prefetch all content, I highly recommend we have some sort of indicator for non-prefetched content loads at least. Even un-indicated loading delays of under 400ms can create a confusing UX wherein the user isn't confident their action has triggered any change. I'd rather have a progress bar or indicator flash for 100ms then go away than have the user wonder during that time if their click did anything.

> A pushback that I heard was the loading bar we were using (nprogress), seems like it would just be covered up with the loading bar on mobile. On desktop, you should be able to see that the page is still loading from all the cues the browser gives you.

Where did we get this pushback for mobile, and what cues specifically are given by the browser on desktop? 

In my testing on desktop, the browser isn't giving me any indication of a state change when I click into category or platform pages re: above. The URL path doesn't even seem to change instantly upon click.

> Also please make sure to be testing page speed (and the need/desire for a loader) on stage.

All my tests are on staging.app.co to be clear.

**Comment by markmhx** [comment]
@hstove @aulneau Can I get your latest thoughts on this issue?

**Comment by hstove** [comment]
I just did a quick browse-through, and every page seemed to load in < 300ms, which felt instant. I think a loader is not necessary IMO. I think if we find bad spots, we can definitely improve them with a line or two of code. Have you found a slow page?

**Comment by markmhx** [comment]
I'm generally finding load times better than on the server, too, so agree we can at least park this for now until we encounter lagginess again and can't solve it through performance increases.
