### ISSUE TITLE
Fields are always NULL in the admin panel for all apps

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#704]
**Describe the bug**
The following fields are blank for all apps in the admin panel

Submitted By:
Referral Code:
Referral Source:

**To Reproduce**
click on any app go to admin panel and these fields are never poplated

**Expected behavior**
The fields should not always be blank 

**Screenshots**
<img width="1291" alt="Screen Shot 2019-11-24 at 7 33 34 PM" src="https://user-images.githubusercontent.com/49165468/69504566-f6475a80-0ef1-11ea-8cef-8be0dfe8c9b5.png">

**Comment by hstove** [comment]
This is due to the way that staging imports data from production. It only imports public data - and these fields are all not public.

This is not the case on production, and the 'submitted by' field is almost always present. The 'referral source' was added for a campaign that I don't think went anywhere, so most apps won't have it.

If you add an app yourself on staging, the 'submitted by' field should be present.

I'm going to close this - feel free to re-open if you think there is a bug here.
