### ISSUE TITLE
New Maker Portal: Zapier Link in Submission confirmation is visible

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#711]
**Describe the bug**
The submission accepted email includes a link to a Zapier which the user can turn off.

- Can't tell if this is intentional on our part, is it? 
- If it is intentional both the inclusion of the link and the ability to turn off the zap?
- What are the implications for the user of turning the ZAP off? Woudl the user receiving multiple notifications of receipt of submission as implied by the text?

We should explain that to the application submission person

**To Reproduce**
1. Submit an app.
2. Get a confirmation email.
3. Scroll down to the Visit this link to stop these emails. 
4. Click on the link.

![image](https://user-images.githubusercontent.com/1347209/69997991-3e760680-150a-11ea-8208-1b6fe37ca1c3.png)

Also, it is confusing in there is no link to `https://staging.app.co/maker/apps` or *Manage your apps* --- this could present a logic problem if you plan to send that out in a subsequent email.

1. Get submission received.
2. Turn off Zap
? Never receiving a link to Manage my app

**Comment by markmhx** [comment]
The link to "Manage your apps" is being added as part of this issue: https://github.com/blockstack/app.co/issues/599

This Zapier link also appears already in production for these emails, so I assume it's intended for inclusion. @cuevasm is that indeed the case and can you describe the expected behavior here per @moxiegirl's questions?
