### ISSUE TITLE
Submission Text for Authentication Might Cause Confusion 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#716]
Since the authentication section isn't required to submit, people might skip over it and or think that Blockstack is selected when it is not. Can we make the field blank instead of having Blockstack listed there?

**Comment by moxiegirl** [comment]
What you see in the fields are help text. If the user doesn't enter anything there, the system and they want to participate in app mining, they will get an error message saying to enter something.

Tho, I do agree the help text just looks like defaults in this design. We might want to do something like this instead. 

![image](https://user-images.githubusercontent.com/1347209/70396720-6f22d800-1a03-11ea-8c02-841862dda103.png)

Rather than just some faint entry that implies a default rather than a choice..
