### ISSUE TITLE
Post submission dialog has incorrect rollover and has confusing labeling

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#751]
@markmhx as I understand you, once they click *Submit your app* they go directly to this dialog:

![image](https://user-images.githubusercontent.com/1347209/70565007-2137dc80-1b89-11ea-9e1a-b096a2c5b007.png)

At this point, the user has already indicated they want to participate in app mining, on the preceding **Submit your app** dialog. This is evidenced by two  facts 1) The user has a user had to choose **Blockstack Auth** and 2) the user had to agree to app mining terms to even see this dialog.

It follows logically,  by submitting an app and clicking agree they are already _participating_ in app mining. The proper label for this button appears as follows:

![image](https://user-images.githubusercontent.com/1347209/70566389-e1262900-1b8b-11ea-9b49-7162c88fd076.png)

Note on the button label the word app is singular but it still reinforces the menu item *Manage your apps* plural. Additionally, we should adjust the language in the dialog (see highlight) above.

( I actually prefer manage your submission but 1) I was pretty sure you'd think that too long for the menu and it isn't clear to me yet if there are management dialogs associated with non-blockstack-auth apps -- I think no because I couldn't get them to show but maybe that is a bug.)

**NOTE ANOTHER PROBLEM**: The rollover label should be changed to match the button label -- it currently reads "Submit your app" at least in the version I am running.

**Comment by markmhx** [comment]
There is indeed a bit of confusion here given how we're ordering certain things and using language inconsistently. Here's what I propose:

First off, on the "Submission received" page, we should _not_ say the user is "eligible to participate in App Mining" since that's a confusing use of "eligible" when we they aren't actually "eligible for App Mining" until they complete the subsequent page (upon clicking the button). Note on that page how we say in the right-hand column "Complete these sections to become eligible for App Mining".

As such, let's change the copy on this "Submission received" page here to "Because your app uses Blockstack authentication, you are invited to participate in [App Mining](https://app.co/mining)".

The button should also be change to "Submit information for App Mining" since the subsequent page is titled "App Mining submission". That lines up the language more consistently across the transition.

However, in turn we should update this last line of copy to "To participate, you are required to provide payment details, identity verification and legal documents" since that reflects the actual information we'll collect more accurately.

I agree it's a bit strange that we ask the user to accept App Mining terms _before_ we later ask them to provide this additional information for App Mining. However, it doesn't mean they're already participating in App Mining or otherwise eligible having submitted only the "Submit your app" form. I suppose we put these terms into that first form simply out of convenience, so we don't have to ask for compliance later. Note as well how we're asking even non-Blockstack app submitters to accept App Mining terms then. 🤷‍♂

Also note that on the "Manage your apps" page, all apps – both Blockstack and non-Blockstack app – show up for a user.  We don't have anything for developers to edit there with non-Blockstack apps, at least yet. But the idea is that we might (e.g. they could edit app titles, logos, etc. one day).

Most important out of all this is indicating with the "Submit information for App Mining" button (or some similar label copy) that it's a CTA to participate in App Mining. If we were to label this as something generic in this context like "Manage your app", the user is likely to get confused about what they're being asked to do (which is _not_ simply managing their app generally).

@moxiegirl what do you think of all the above? If you believe the terms UX will confuse people, perhaps @jasperjansz can take another look at its placement.

**Comment by moxiegirl** [comment]
@markmhx my non-Blockstack auth submission doesn't show up under *Manage your apps*.  That makes sense if clicking on it actually needs no where

cc: @timstackblock  to confirm this is what is testing out.

**Comment by markmhx** [comment]
@kyranjamie is going to double check but he believes non-Blockstack apps _should_ show up on the "Manage your apps" page. And they'd lead to a page saying basically "There's nothing to do with non-Blockstack app management for now" (a sub-optimal dead-end to be fair, but I think okay for now).

I'm cool with an approach like the one you describe here for the app submission confirmation page. Could we label this button "Complete your App Mining submission", though, to use "App Mining" consistently there?

And yep, we're aware there's no button for non-Blockstack apps here since we don't need to encourage them to do anything management or App-Mining wise at this point.

**Comment by kyranjamie** [comment]
There was a regression where the check for non-blockstack apps was gone. Fixed this in 6c7ada0.

Checked behaviour and non-blockstack apps do appear in app list.
