### ISSUE TITLE
Redirect all /mining/* paths to App Mining blog post

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#767]
Now that App Mining is paused, it's cleanest to redirect all traffic to App Mining pages on App.co to the blog post about that pause: https://blog.blockstack.org/the-next-phase-of-app-mining/

That includes all traffic to https://app.co/mining and any monthly results pages such as https://app.co/mining/january-2020, which are experiencing show-stopping bugs anyway (https://github.com/blockstack/app.co/issues/760 and https://github.com/blockstack/app.co/issues/764).

@GinaAbrams @cuevasm @hstove this appears to be the most expedient solution to these App.co problems, given we don't currently want to invest a lot of timing debugging app loading issues. Does this work for you three?

**Comment by GinaAbrams** [comment]
We already have a new page on app.co/mining. It's nice to have a history of the program. Can we reconsider?

**Comment by GinaAbrams** [comment]
We already have a new page on app.co/mining. It's nice to have a history of the program. How long would it take to fix?

**Comment by cuevasm** [comment]
+1, this is a clunky solution, historical data should stay available, redirecting all mining pages would make them inaccessible

**Comment by cuevasm** [comment]
I could make the case just based on SEO value

**Comment by markmhx** [comment]
What kinds of SEO terms are we trying to capture with these pages?

I realize it's a clunky solution but App.co is a bit of despair development-wise at the moment. I can't really stress that enough. And unless we have clear business goals for retaining these pages, I'd prefer to start redirecting them. We have these bugs today, but we're likely to have even more tomorrow, then the day after, etc.

**Comment by markmhx** [comment]
Also, the problem with this being a pit of despair is that it's hard to even estimate how long it'll take to fix. This was the core reason our Maker Portal sprint kept extending and extending.

**Comment by hstove** [comment]
So, the solution to wanting less app.co work is more app.co work? 😛

These pages are already updated for the pause announcement, and the reason the results page was broken was due to a user error (I didn't fill out the admin report page fully), then exacerbated by a different bug that didn't allow admins to login.

Jokes aside, I understand this request. I would agree with Gina/Mitchell that the value of having these results pages is worth simply not touching it. We need to fix this admin login bug, regardless of app mining. I guess I just mainly disagree with the cost analysis that your requested change is more work than fixing #764 and #760.

**Comment by markmhx** [comment]
I'm glad it was fast enough to fix these two bugs after all. I was wary that #764 in particular was rooted in a more difficult problem, and I'm still generally wary that we're maintaining brittle surface area with App.co. But hopefully that latter concern won't bear out and things will remain stable.

Closing this out; the App Mining pages are spared for now 😉
